# Configuration file for Retail Customer Segmentation POC
# This file contains all configurable parameters for the segmentation pipeline

# Project Information
project:
  name: "Retail Customer Segmentation POC"
  version: "0.1.0"
  description: "Customer segmentation using fuzzy clustering and neural networks with MCP integration"

# Directory Paths
paths:
  # Data directories
  data_dir: "data"
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  output_dir: "data/output"
  
  # Visualization directories
  visualizations_dir: "visualizations"
  
  # Model directories
  models_dir: "models"
  checkpoints_dir: "models/checkpoints"
  
  # Source data files
  source_data:
    product_hierarchy: "data/product_hierarchy.csv"
    customer_sales_enriched: "data/customer_sales_data_enriched.csv"
    customer_sales_legacy: "data/customer_sales_data.csv"
  
  # Output files
  output_files:
    customers_with_segments: "data/customers_with_segments.csv"
    segments_for_ai: "data/customer_segments_for_ai.json"
    cluster_report: "data/cluster_report.txt"
    
  # Visualization outputs
  visualization_files:
    cluster_distribution: "visualizations/cluster_distribution.png"
    segment_characteristics: "visualizations/segment_characteristics.png"
    rfm_scatter: "visualizations/rfm_scatter.png"
    membership_heatmap: "visualizations/membership_heatmap.png"
    department_preferences: "visualizations/department_preferences.png"
    size_distribution: "visualizations/size_distribution.png"

# Data Generation Configuration
data_generation:
  n_customers: 500
  random_seed: 42
  
  # Faker settings for realistic profile fields
  faker:
    enabled: true      # Toggle to include first_name, last_name, email, phone, address, etc.
    locale: "en_US"   # Locale for Faker profile data (e.g., en_US, en_GB, fr_FR)
  
  # Customer segment distribution (must sum to 1.0)
  segment_probabilities:
    high_value_frequent: 0.20      # Segment 1
    medium_value_regular: 0.35     # Segment 2
    low_value_occasional: 0.30     # Segment 3
    churned_inactive: 0.15         # Segment 4
  
  # Segment characteristics
  segments:
    high_value_frequent:
      total_purchases: [50, 100]
      avg_order_value: [150, 300]
      recency_days: [1, 30]
      frequency_per_month: [4, 8]
      return_rate: [0.01, 0.05]
    
    medium_value_regular:
      total_purchases: [15, 50]
      avg_order_value: [75, 150]
      recency_days: [15, 60]
      frequency_per_month: [1.5, 4]
      return_rate: [0.05, 0.15]
    
    low_value_occasional:
      total_purchases: [3, 15]
      avg_order_value: [30, 75]
      recency_days: [30, 120]
      frequency_per_month: [0.3, 1.5]
      return_rate: [0.10, 0.25]
    
    churned_inactive:
      total_purchases: [1, 5]
      avg_order_value: [20, 60]
      recency_days: [120, 365]
      frequency_per_month: [0.05, 0.3]
      return_rate: [0.20, 0.40]
  
  # Enriched feature definitions - Product Hierarchy
  # Note: Classes belong to departments in retail hierarchy
  departments:
    "Accessories & Footwear":
      classes:
        - "Bags & Wallets"
        - "Soft & Hard Accessories"
    "Health & Wellness":
      classes:
        - "Consumables"
        - "Personal Care"
    "Home & Lifestyle":
      classes:
        - "Bedding"
  
  child_ages:
    - "Baby"
    - "Child"
  
  adult_sizes:
    - "XS"
    - "S"
    - "M"
    - "L"
    - "XL"

# Column Definitions
columns:
  # Core customer features
  core_features:
    customer_id:
      type: "string"
      description: "Unique customer identifier"
      format: "CUST_XXXXX"
    
    total_purchases:
      type: "integer"
      description: "Total number of purchases made by customer"
      min: 0
    
    total_revenue:
      type: "float"
      description: "Total revenue generated by customer"
      min: 0.0
      unit: "USD"
    
    avg_order_value:
      type: "float"
      description: "Average order value per transaction"
      min: 0.0
      unit: "USD"
    
    recency_days:
      type: "integer"
      description: "Days since last purchase (Recency)"
      min: 0
    
    frequency_per_month:
      type: "float"
      description: "Average purchase frequency per month (Frequency)"
      min: 0.0
    
    customer_lifetime_months:
      type: "float"
      description: "Total months as a customer"
      min: 0.0
    
    return_rate:
      type: "float"
      description: "Percentage of returned items"
      min: 0.0
      max: 1.0
    
    true_segment:
      type: "integer"
      description: "Ground truth segment for validation"
      values: [1, 2, 3, 4]
  
  # Department enriched features
  department_features:
    pattern: "dept_total_value_{department_name}"
    type: "float"
    description: "Total value of purchases in this department"
    unit: "USD"
    departments:
      - "Accessories & Footwear"
      - "Health & Wellness"
      - "Home & Lifestyle"
  
  department_units:
    pattern: "dept_total_units_{department_name}"
    type: "integer"
    description: "Total units purchased in this department"
    departments:
      - "Accessories & Footwear"
      - "Health & Wellness"
      - "Home & Lifestyle"
  
  # Class enriched features
  class_features:
    pattern: "class_total_value_{class_name}"
    type: "float"
    description: "Total value of purchases in this class"
    unit: "USD"
    classes:
      - "Bags & Wallets"
      - "Soft & Hard Accessories"
      - "Consumables"
      - "Personal Care"
      - "Bedding"
  
  class_units:
    pattern: "class_total_units_{class_name}"
    type: "integer"
    description: "Total units purchased in this class"
    classes:
      - "Bags & Wallets"
      - "Soft & Hard Accessories"
      - "Consumables"
      - "Personal Care"
      - "Bedding"
  
  # Size/Age breakdown features
  child_age_features:
    pattern: "count_{age_group}"
    type: "integer"
    description: "Count of items for this age group"
    age_groups:
      - "Baby"
      - "Child"
  
  adult_size_features:
    pattern: "count_size_{size}"
    type: "integer"
    description: "Count of items in this adult size"
    sizes:
      - "XS"
      - "S"
      - "M"
      - "L"
      - "XL"
  
  # Cluster assignment columns (generated during segmentation)
  cluster_features:
    fuzzy_cluster:
      type: "integer"
      description: "Fuzzy clustering cluster assignment"
    
    neural_cluster:
      type: "integer"
      description: "Neural network clustering cluster assignment"
    
    segment_name:
      type: "string"
      description: "Human-readable segment name"
    
    fuzzy_membership_pattern:
      pattern: "fuzzy_membership_cluster_{cluster_id}"
      type: "float"
      description: "Fuzzy membership degree for this cluster"
      min: 0.0
      max: 1.0

# Product Hierarchy Configuration
product_hierarchy:
  file: "data/product_hierarchy.csv"
  columns:
    id:
      type: "integer"
      description: "Unique product hierarchy identifier"
    
    gender_age:
      type: "string"
      description: "Target gender/age demographic"
      values: ["Adult", "Woman", "Man", "Child", "Baby", "Unknown"]
    
    normalized_department:
      type: "string"
      description: "Normalized department name"
    
    normalized_class:
      type: "string"
      description: "Normalized class name"
    
    normalized_subclass:
      type: "string"
      description: "Normalized subclass name"

# Fuzzy Clustering Configuration
fuzzy_clustering:
  n_clusters: 4
  fuzziness_parameter: 2.0  # m parameter for FCM
  max_iterations: 150
  tolerance: 1e-5
  random_seed: 42
  
  # Feature selection for clustering
  features_to_use:
    - "total_purchases"
    - "total_revenue"
    - "avg_order_value"
    - "recency_days"
    - "frequency_per_month"
    - "customer_lifetime_months"
    - "return_rate"

# Neural Clustering Configuration
neural_clustering:
  n_clusters: 4
  encoding_dim: 10
  hidden_layers: [64, 32, 16]
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  random_seed: 42
  verbose: 0
  
  # Feature selection for clustering
  features_to_use:
    - "total_purchases"
    - "total_revenue"
    - "avg_order_value"
    - "recency_days"
    - "frequency_per_month"
    - "customer_lifetime_months"
    - "return_rate"

# Cluster Enrichment Configuration
cluster_enrichment:
  # Minimum cluster size to consider valid
  min_cluster_size: 5
  
  # Percentile thresholds for characterization
  percentiles:
    high_threshold: 75
    medium_threshold: 50
    low_threshold: 25
  
  # Export configuration
  export_format: "json"
  include_recommendations: true
  max_strategies_per_segment: 5

# Visualization Configuration
visualization:
  dpi: 150
  figure_format: "png"
  style: "seaborn-v0_8"
  color_palette: "Set2"
  
  # Figure sizes
  figure_sizes:
    default: [12, 6]
    distribution: [14, 5]
    characteristics: [15, 10]
    scatter: [15, 5]
    heatmap: [12, 6]
    department_prefs: [14, 6]
    size_dist: [15, 5]
  
  # Plot parameters
  plot_params:
    alpha: 0.7
    rotation: 45
    grid_alpha: 0.3
    sample_size_heatmap: 50

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file: "logs/segmentation.log"
  console_output: true

# Performance Configuration
performance:
  n_jobs: -1  # Number of parallel jobs (-1 = all cores)
  cache_data: true
  memory_limit_mb: 4096
